name: 215a
channels:
  - defaults
dependencies:
  - python
  - pip:
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyterlab
    - pytorch
    - torch
    - torchvision
    - lightning
